### ISSUE TITLE
Upgrading to PagedList 1.15 breaks code analysis

### ISSUE THREAD

**Issue by Thieum** [troygoode/MembershipStarterKit#31]
Upgrading to PagedList 1.15 breaks code analysis as PagedList is referenced with a specific version in MVCMembership :

CA0058 : The referenced assembly 'PagedList, Version=1.14.0.0, Culture=neutral, PublicKeyToken=abbb863e9397c5e1' could not be found. This assembly is required for analysis and was referenced by: --\MvcMembership.3.7.0\lib\40\MvcMembership.dll.

**Comment by troygoode** [comment]
Fixed with version 3.8.0 on NuGet.

**Comment by ahaverdings** [comment]
Upgrading to PagedList 1.17 breaks code analysis as PagedList is referenced with a specific version in MVCMembership:

CA0058  Error Running Code Analysis CA0058 : The referenced assembly 'PagedList, Version=1.15.0.0, Culture=neutral, PublicKeyToken=abbb863e9397c5e1' could not be found. This assembly is required for analysis and was referenced by: --\MvcMembership.3.8.0\lib\40\MvcMembership.dll.

**Comment by liamjohannes** [comment]
Bump, this is still an issue with MvcMembership 3.8.0 and PagedList 1.17.0.
The referenced assembly 'PagedList, Version=1.15.0.0...
